# Generated by Django 5.2.3 on 2025-06-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tilat', '0001_initial'),
        ('varaajat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varauspaiva', models.DateField()),
                ('tila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilat.tila')),
                ('varaaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varaajat.varaaja')),
            ],
        ),
    ]
