# Generated by Django 5.2.3 on 2025-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayttaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('tunnus', models.CharField(max_length=100)),
                ('salasana', models.CharField(max_length=100)),
                ('rooli', models.CharField(max_length=100)),
            ],
        ),
    ]
