# Generated by Django 5.2.3 on 2025-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayttaja',
            name='rooli',
            field=models.CharField(choices=[('admin', 'Ylläpitäjä'), ('user', 'Käyttäjä')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kayttaja',
            name='salasana',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='kayttaja',
            name='tunnus',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
